name: Weekly Newsletter (build & send)

on:
  schedule:
    # 每周一 09:00 America/New_York 触发（= 13:00 UTC）
    - cron: "0 13 * * 1"
  workflow_dispatch: {}  # 手动触发备用

jobs:
  build-and-send:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          fi
          # 兜底（即使没有 requirements.txt 也能运行）
          pip install requests jinja2 python-dateutil python-dotenv

      - name: Generate newsletter HTML
        env:
          TECHSUM_API_KEY: ${{ secrets.TECHSUM_API_KEY }}
        run: |
          set -e
          python scripts/api.py
          echo "Generated files:"
          ls -lt output

      - name: Pick latest HTML & set subject
        id: pick
        run: |
          set -e
          FILE=$(ls -t output/newsletter-*.html | head -n 1)
          if [ -z "$FILE" ]; then
            echo "No newsletter HTML found in output/"; exit 1
          fi
          echo "file=$FILE" >> $GITHUB_OUTPUT

          # 纽约时区日期作为主题尾巴
          DATE_NY=$(TZ=America/New_York date +%Y-%m-%d)
          SUBJECT="TechSum Weekly · ${DATE_NY}"
          echo "subject=$SUBJECT" >> $GITHUB_OUTPUT
          echo "Picked: $FILE"
          echo "Subject: $SUBJECT"

      - name: Send preview email
        env:
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
          MAIL_TO:    ${{ secrets.MAIL_TO }}
        run: |
          set -e
          python scripts/send_email.py --file "${{ steps.pick.outputs.file }}"


      - name: Upload artifact (latest HTML)
        uses: actions/upload-artifact@v4
        with:
          name: newsletter-latest
          path: ${{ steps.pick.outputs.file }}
          if-no-files-found: error
